export const enTranslations: { [k: string]: string } = {
  Dashboard: "Dashboard",
  Categories: "Categories",
  "Category List": "Category List",
  "Add Category": "Add Category",
  "Create Category": "Create Category",
  "Edit Category": "Edit Category",
  Name: "Name",
  Description: "Description",
  Active: "Active",
  "Created at": "Created at",
  Save: "Save",
  "Save and continue editing": "Save and continue editing",
  // CATEGORY
  "Category saved with success": "Category saved with success",
  // DATA TABLE
  "No match records found": "No match records found",
  Sort: "Sort",
  "Next page": "Next page",
  "Previous page": "Previous page",
  "Rows per page:": "Rows per page:",
  of: "of",
  Search: "Search",
  "Download CSV": "Download CSV",
  Print: "Print",
  "View Columns": "View Columns",
  "Filter Table": "Filter Table",
  All: "All",
  Filters: "Filters",
  Reset: "Reset",
  "Show table columns": "Show table columns",
  "row(s) selected": "row(s) selected",
  Delete: "Delete",
  "Delete selected columns": "Delete selected columns",
  Actions: "Actions",
  Loading: "Loading",
  "Unable to load data": "Não foi possível carregar as informações",
  "Clear search": "Clear search",
};
