export const ptBrTranslations: { [k: string]: string } = {
  Dashboard: "Painel",
  Categories: "Categorias",
  "Category List": "Listagem de Categorias",
  "Add Category": "Adicionar Categoria",
  "Create Category": "Criar Categoria",
  "Edit Category": "Editar Categoria",
  Name: "Nome",
  Description: "Descrição",
  Active: "Ativo",
  "Created at": "Criado em",
  Save: "Salvar",
  "Save and continue editing": "Salvar e continuar editando",
  // CATEGORY
  "Category saved with success": "Categoria salva com sucesso",
  // DATA TABLE
  "No match records found": "Nenhum registro encontrado",
  Sort: "Classificar",
  "Next page": "Próxima página",
  "Previous page": "Página anterior",
  "Rows per page:": "Linhas por página:",
  of: "de",
  Search: "Buscar",
  "Download CSV": "Download CSV",
  Print: "Imprimir",
  "View Columns": "Ver Colunas",
  "Filter Table": "Filtrar Tabelas",
  All: "Todos",
  Filters: "Filtros",
  Reset: "Limpar",
  "Show table columns": "Ver/Esconder colunas da tabela",
  "row(s) selected": "registros(s) selecionados",
  Delete: "Deletar",
  "Delete selected columns": "Deletar colunas selecionadas",
  Actions: "Ações",
  Loading: "Carregando",
  "Unable to load data": "Não foi possível carregar as informações",
};
